version: '3.8'

volumes:
  pg-tenant:

x-postgres-common:
  &postgres-common
  image: postgres:16-alpine
  user: postgres
  restart: always
  healthcheck:
    test: 'pg_isready -U user --dbname=wms_tenant'
    interval: 10s
    timeout: 5s
    retries: 5

services:
  postgres_primary:
    <<: *postgres-common
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: wms_tenant
      POSTGRES_PASSWORD: pass
    volumes:
      - pg-tenant:/var/lib/postgresql/data